-- Run this script in the Supabase SQL Editor to set up your tables

-- 1. Create table for Dues
create table if not exists public.dues (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  biller text,
  billing_date date,
  amount numeric,
  due_date date,
  executive text,
  remarks text,
  is_paid boolean default false,
  paid_on date
);

-- 2. Create table for Orders
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  biller text,
  order_placed_on date,
  order_items text,
  transport text,
  drive_link text,
  executive text
);

-- 3. Create table for Billers
-- Note: Column names are quoted to match the camelCase used in your frontend code
create table if not exists public.billers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  "creditDuration" numeric,
  "accountNo" text,
  ifsc text,
  "bankName" text,
  branch text,
  executive text
);

-- 4. Set up permissions (Row Level Security)
-- This allows any visitor with your Anon Key to read/write/update/delete.
-- For a real production app, you might want strict user-based policies later.

alter table public.dues enable row level security;
alter table public.orders enable row level security;
alter table public.billers enable row level security;

create policy "Public Access Dues" on public.dues for all using (true) with check (true);
create policy "Public Access Orders" on public.orders for all using (true) with check (true);
create policy "Public Access Billers" on public.billers for all using (true) with check (true);
